comment_width = 100
max_width = 120
edition = "2021"
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
trailing_comma = "Vertical"
fn_params_layout = "Vertical"
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
